version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thanks-web-app
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: node dist/main.js
    ports:
      - 8080:8080
